//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACS_Training.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACS_Training.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Computer Science Training.
        /// </summary>
        public static string applicationTitle {
            get {
                return ResourceManager.GetString("applicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to content.json.
        /// </summary>
        public static string fileName {
            get {
                return ResourceManager.GetString("fileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string flowDirection {
            get {
                return ResourceManager.GetString("flowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the given statement, please choose the subtopic it belongs to.
        /// </summary>
        public static string questionDescription {
            get {
                return ResourceManager.GetString("questionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check.
        /// </summary>
        public static string quizCheckButton {
            get {
                return ResourceManager.GetString("quizCheckButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        public static string quizCorrect {
            get {
                return ResourceManager.GetString("quizCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct answer is : .
        /// </summary>
        public static string quizCorrectAnswerText {
            get {
                return ResourceManager.GetString("quizCorrectAnswerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz Topic :.
        /// </summary>
        public static string quizHeading {
            get {
                return ResourceManager.GetString("quizHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect.
        /// </summary>
        public static string quizIncorrect {
            get {
                return ResourceManager.GetString("quizIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string quizNextButton {
            get {
                return ResourceManager.GetString("quizNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Option not found.
        /// </summary>
        public static string quizOptionError {
            get {
                return ResourceManager.GetString("quizOptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an option.
        /// </summary>
        public static string quizOptionErrorMessage {
            get {
                return ResourceManager.GetString("quizOptionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quiz.
        /// </summary>
        public static string quizTitle {
            get {
                return ResourceManager.GetString("quizTitle", resourceCulture);
            }
        }
    }
}
